version: "3.4"

services:
  tester:
    build: tester
    command: python test.py
    volumes:
      - ./tester:/code
  minioserver:
    image: minio/minio:RELEASE.2020-09-26T03-44-56Z
    command: server /export
    ports:
      - 9000:9000
    environment:
      MINIO_ACCESS_KEY: weak_access_key
      MINIO_SECRET_KEY: weak_secret_key
    volumes:
        - ./test:/export

networks:
  default:


  
